AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ECE 461 Trustworthy Model Registry - Single Lambda Proxy Deployment

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: python3.12
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref TrustModelRegistryTable

Resources:
  ############################################################
  # DynamoDB TABLE
  ############################################################
  TrustModelRegistryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TrustModelRegistry
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  ############################################################
  # API Gateway - HTTP API (v2) with single ANY proxy route
  ############################################################
  RegistryApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: "$default"
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
        AllowHeaders: ["*"]

  ############################################################
  # SINGLE LAMBDA FOR ALL ENDPOINTS
  ############################################################
  RegistryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TrustModelRegistryTable
      Events:
        # ONE CATCH-ALL PROXY ROUTE
        ProxyRoute:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref RegistryApi

Outputs:
  ApiUrl:
    Value: !Sub "https://${RegistryApi}.execute-api.${AWS::Region}.amazonaws.com"
    Description: Base URL of the Registry API

  TableName:
    Value: !Ref TrustModelRegistryTable
    Description: Name of the DynamoDB table
